### ISSUE TITLE
fontforge package not found in the python path

### ISSUE THREAD

**Issue by bishoymoussa** [carrasti/pysvg2font#2]
fontforge package not found in the python path

How can I solve this problem?

**Comment by carrasti** [comment]
@bishoymoussa  if you are running some linux system with apt you can try

```
sudo apt install fontforge python3-fontforge
```

If not you can always use a docker image, for example `[debian:stable-slim](https://hub.docker.com/layers/debian/library/debian/stable-slim/images/sha256-1086096bcb743c4d04ad1edc0fe729fe536442049d76894172c8ed1fdbb4a48b?context=explore) mounting a volume with local filesyestem and install fonforge there.
