### ISSUE TITLE
TypeError: 'cmp' is an invalid keyword argument for sort()

### ISSUE THREAD

**Issue by manhvela** [carrasti/pysvg2font#3]
Hello there,

I followed your instructions but I get the following error:

> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/manhvela/Desktop/pysvg2font-master/pysvg2font/__main__.py", line 37, in <module>
>     fontgenerator=SvgToFontGenerator(args.svg_source_directory,
>   File "/home/manhvela/Desktop/pysvg2font-master/pysvg2font/__init__.py", line 71, in __init__
>     self.source_svg_files = self.collect_svg_files()
>   File "/home/manhvela/Desktop/pysvg2font-master/pysvg2font/__init__.py", line 97, in collect_svg_files
>     svg_files.sort(cmp=lambda a, b: a.name.lower() > b.name.lower)
> TypeError: 'cmp' is an invalid keyword argument for sort()

Could you help me?

**Comment by carrasti** [comment]
Hi, it is a while I don't use and mainatin this library, and it is quite likely it is not compatible with modern python. I believe the `cmp` argument has been removed from list sort() method in favour of `key`, some background here https://docs.python.org/3/howto/sorting.html#the-old-way-using-the-cmp-parameter

**Comment by manhvela** [comment]
> Hi, it is a while I don't use and mainatin this library, and it is quite likely it is not compatible with modern python. I believe the `cmp` argument has been removed from list sort() method in favour of `key`, some background here https://docs.python.org/3/howto/sorting.html#the-old-way-using-the-cmp-parameter

Thanks.
