### ISSUE TITLE
Bad RGB color spec

### ISSUE THREAD

**Issue by manhvela** [carrasti/pysvg2font#4]
I tried running your code with my own svgs but I get a bunch of these messages "Bad RGB color spec: rgb(some_random_number)
The .ttf gets produced but its empty.

**Comment by carrasti** [comment]
Hey, sorry for the late reply, I always try to do monochrome svg consisting on a single path. I usually edit my svgs in inkscape or other tools so that they are a single path, you can use the path combining and cutting operations for that.

**Comment by manhvela** [comment]
> Hey, sorry for the late reply, I always try to do monochrome svg consisting on a single path. I usually edit my svgs in inkscape or other tools so that they are a single path, you can use the path combining and cutting operations for that.

Thanks,

one more question, how can I define in which slots of .ttf the svgs are going to be placed??

**Comment by manhvela** [comment]
> > Hey, sorry for the late reply, I always try to do monochrome svg consisting on a single path. I usually edit my svgs in inkscape or other tools so that they are a single path, you can use the path combining and cutting operations for that.
> 
> Thanks,
> 
> one more question, how can I define in which slots of .ttf the svgs are going to be placed??

ok I managed it,

thank you for the answer you can close this issue.
